## REQUIRED ##
# 우선 쿠버네티스 API 버전, 리소스의 유형을 적어주어야 한다
apiVersion: v1
kind: Pod

## METADATA ##
# 메타데이터는 해당 리소스를 식별하기 위한 정보이다
# 이름(Required)과 레이블, 네임스페이스 등(Option)을 작성할 수 있다
metadata:
  name: pod-1

## SPEC ##
# 스펙은 리소스의 상태나 정보를 실제로 정의하는 부분이다
# pod의 경우 실행할 컨테이너를 정의해야 하며, 볼륨이나 Service, Security Context 등을 정의할 수도 있다
spec:
  ## CONTAINER ##
  # 컨테이너를 정의하는 부분으로, 이름과 이미지로 정의될 수 있으며, 도커처럼 볼륨 등을 정의할 수 있다
  containers:
    - name: nginx-pod-1
      image: nginx
