# 헤드리스 서비스
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: Endpoints
metadata:
  name: db-service
subsets:
  - addresses:
      # 로컬에 별도로 띄운 DB 서버
      - ip: 192.168.0.14
    ports:
      - port: 5432