## NodePort SERVICE ##
# 모든 노드의 특정 포트(NodePort)에 서비스를 연결하는 방식. 노드가 인식할 수 있어야하기에 ClusterIP 방식으로 private IP를 부여한다
# 별도의 오브젝트 없이 홀로 동작하며, 노드 뒷단에 위치하여 들어온 요청을 대상 파드로 적절히 전달된다
# 단순히 외부와 통신할 수 있는 ClusterIP라고 보면 된다

## 동작 과정
### 생성 시
# 모든 노드에 사용할 포트를 미리 개발
# NorPort 서비스 생성

### 요청을 받을 시
# 임의의 노드로 요청이 들어옴
# 노드의 특정 포트와 연결된 NodePort 서비스가 요청을 받음
# 서비스는 해당하는 파드로 요청을 전달

## 장점
# 별도의 로드밸런서가 필요없다
# 간단하게 외부에 노출할 수 있다

## 단점
# 모든 노드에 포트가 이미 열려있어야 한다 -> 생성과 동시에 포트를 열어주는 로드밸런서와 달리 유연하지 못함
# 단지 모든 노드를 통해 요청을 보낼 수 있다는 것일 뿐, 특정 노드에 직접 요청해야 한다 -> 노드는 변경(생성 및 삭제)이 자유롭기에 엔드포인트가 수시로 바뀐다. 때문에 다중 노드 클러스터에서 로드밸런싱 효과를 얻을 수 없음
# 모든 노드에 대해 바꿔야하기 때문에 SSL 적용 라우팅 같은 복잡한 설정은 어렵다
# 지원하는 트래픽 분산 정책(External/Internal 트래픽 정책 등)이 없이 무조건 파드 균등 분산이다 -> 지원하는 분산 수준도 로드밸런서 서비스와 차이가 있다

# 사용 케이스(거의 없는듯?)
# 노드가 1개인 경우
# 노드가 생성/삭제되지 않는 경우
apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  selector:
    app: service-base-deployment-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

  type: NodePort