apiVersion: v1
kind: Service
metadata:
  name: selector-headless-service
spec:
  clusterIP: None
  selector:
    app: service-base-deployment-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
