apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: front-filebeat
spec:
  type: filebeat
  version: 8.17.2
  config:
    filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/infra-frontend-*.log

    output.logstash:
      hosts: [ "logstash-ls-beats.default.svc:5043" ]
      ttl: 120
  daemonSet:
    podTemplate:
      spec:
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        securityContext:
          runAsUser: 0
        containers:
          - name: filebeat
            volumeMounts:
              - name: varlogcontainers
                mountPath: /var/log/containers
              - name: varlogpods
                mountPath: /var/log/pods
              - name: varlibdockercontainers
                mountPath: /var/lib/docker/containers
        volumes:
          - name: varlogcontainers
            hostPath:
              path: /var/log/containers
          - name: varlogpods
            hostPath:
              path: /var/log/pods
          - name: varlibdockercontainers
            hostPath:
              path: /var/lib/docker/containers
