apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-persistence
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /volumes/localpv
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: volume
              operator: In
              values:
                - local

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-persistent-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Mi
  storageClassName: local-storage
